language: go
go:
- '1.12'
before_install:
- openssl aes-256-cbc -K $encrypted_5add2d609613_key -iv $encrypted_5add2d609613_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
- docker login -u $DOCKER_ID -p $DOCKER_PASS
- docker build -t oddsread/read-api .
- docker push oddsread/read-api

install: 
- ssh -i ./deploy_rsa -oStrictHostKeyChecking=no -t nc-user@mac.odds.team "cd readodds && docker-compose pull && docker-compose up -d"
