language: ruby
services:
- docker
before_install:
- openssl enc -aes-256-cbc -d -in deploy_api_rsa.enc -out deploy_rsa -k $DECRYPT_PASS
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa
- docker login -u $DOCKER_ID -p $DOCKER_PASS
- docker build -t oddsread/read-api .
- docker push oddsread/read-api

install: 
- ssh -i ./deploy_rsa -oStrictHostKeyChecking=no -t $HOST_SERVER "cd readodds && docker-compose pull && docker-compose up -d"
